local defaultBackdropTexture = "Interface/BUTTONS/WHITE8X8"

local colors = {
  blue = CreateColorFromHexString("FF1A4A6B"),
  blueHover = CreateColorFromHexString("FF2A5A7B"),
  blueDark = CreateColorFromHexString("FF16405C"),
  blueFocus = CreateColorFromHexString("FF5980BF"),
  white = CreateColorFromHexString("FFFFFFFF"),
  grayLight = CreateColorFromHexString("FFD9D9D9"),
  grayMuted = CreateColorFromHexString("FF999999"),
  grayDark = CreateColorFromHexString("FF2E2E33"),
  grayDarker = CreateColorFromHexString("FF232B31"),
  grayBorder = CreateColorFromHexString("FF595966"),
  grayBorderLight = CreateColorFromHexString("FF73737F"),
  grayHover = CreateColorFromHexString("FF474752"),
  grayRow = CreateColorFromHexString("FF29292E"),
  grayRowHover = CreateColorFromHexString("FF47474D"),
  grayPageHover = CreateColorFromHexString("FF525257"),
}

LiqUI.Config = {
  shared = {
    backdropTexture = defaultBackdropTexture,
  },
  control = {
    backgroundColor = colors.grayDark,
    backgroundColorHover = colors.grayHover,
    backgroundColorPressed = colors.grayDarker,
    borderColor = colors.grayBorder,
    borderColorHighlight = colors.grayBorderLight,
    borderColorFocus = colors.blueFocus,
    backdrop = {
      bgFile = defaultBackdropTexture,
      edgeFile = defaultBackdropTexture,
      tile = true,
      tileSize = 8,
      edgeSize = 1,
      insets = { left = 1, right = 1, top = 1, bottom = 1 },
    },
    backdropNoBorder = {
      bgFile = defaultBackdropTexture,
      tile = true,
      tileSize = 8,
    },
    padding = 4,
    height = 24,
    checkSize = 38,
    checkSizeSmall = 14,
    dropdownItemHeight = 22,
    dropdownListMaxHeight = 200,
    colorPickerSwatchSize = 24,
    editBoxTextPaddingH = 6,
  },
  primary = {
    defaultColor = colors.blue,
    hoverColor = colors.blueHover,
    pressedColor = colors.blueDark,
  },
  text = {
    defaultColor = colors.white,
    mutedColor = colors.grayLight,
    placeholderColor = colors.grayMuted,
  },
  sidebar = {
    backgroundColor = colors.grayDarker,
    rowBackgroundColor = colors.grayRow,
    rowBackgroundColorHover = colors.grayRowHover,
    pageSelectedColor = colors.blue,
    pageBackgroundColorHover = colors.grayPageHover,
  },
  form = {
    headerLineColor = colors.grayBorder,
    rowGap = 12,
    labelDescGap = 4,
    labelOffsetY = -2,
  },
  window = {
    titlebarHeight = 30,
    padding = 8,
    titlebarIconLeft = 6,
    titlebarIconSize = 20,
    closeButtonIconSize = 10,
    closeButtonIconColor = { 0.7, 0.7, 0.7, 1 },
    iconCloseTexture = "Interface/AddOns/LiqUI/Media/Icon_Close.blp",
    maxWindowWidthMargin = 100,
  },
  settings = {
    windowWidth = 800,
    windowHeight = 500,
    sidebar = {
      width = 200,
      padding = 8,
      itemHeight = 24,
      pageIndent = 16,
      iconSize = 16,
      arrowWidth = 14,
      arrowHeight = 20,
      arrowAtlas = "shop-header-arrow",
      arrowAtlasDisabled = "shop-header-arrow-disabled",
      arrowAtlasHover = "shop-header-arrow-hover",
      arrowRotationDown = math.pi / 2,
      arrowRotationRight = math.pi,
    },
    form = {
      padding = 8,
      rowSpacingDefault = 20,
      rowSpacingAfterHeader = 4,
      rowSpacingAfterDescription = 10,
      headerLineHeight = 1,
      headerLineGap = 20,
      widgetWidthEdit = 180,
      widgetWidthCheck = 24,
      widgetWidthButton = 120,
      widgetWidthDropdown = 180,
      widgetWidthColor = 24,
    },
  },
}
